language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
#  - pip install coveralls
# command to run tests
script:
  - python tests.py
  - python -m smtpd -n -c DebuggingServer localhost:25
